### ISSUE TITLE
About running this project

### ISSUE THREAD

**Issue by thuyjnt2k1** [TamasPetii/Who-wants-to-be-a-millionaire#1]
![312015705_1155170072099677_184182560706537240_n](https://user-images.githubusercontent.com/86361025/201534951-1ecabcb0-5b21-4a0f-b2f4-240cb3fbc029.png)
can you please teach me how to run this project???
i have tried to run this with lazy fool's instruction but its not worked :((
many thanks!!!

**Comment by TamasPetii** [comment]
Hello!

I added a how to run and compile guide to the README file.

It contains information about:
- Compile and Run from Terminal
- What to do with error: 'thread' is not a member of 'std' 
- How to set up Visual Studio 2022 for this SDL project. (Recommended)

**Comment by thuyjnt2k1** [comment]
i have run it successfuly :>

thank you so much, sir <3
